#!/bin/bash

echo "🚀 ProofLocker Deployment Helper"
echo ""
echo "This will help you deploy to Vercel."
echo ""
echo "STEP 1: Push to GitHub"
echo "----------------------"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: prooflocker"
echo "3. Set to PUBLIC (or Private if you prefer)"
echo "4. DO NOT initialize with README"
echo "5. Click 'Create repository'"
echo ""
read -p "Press ENTER once you've created the GitHub repo..."
echo ""
echo "6. Copy the URL that looks like: https://github.com/YOUR_USERNAME/prooflocker.git"
echo ""
read -p "Paste that URL here: " GITHUB_URL
echo ""

# Add GitHub as remote
git remote add github "$GITHUB_URL" 2>/dev/null || git remote set-url github "$GITHUB_URL"

# Push to GitHub
echo "Pushing to GitHub..."
git push -u github main

echo ""
echo "✅ Code is now on GitHub!"
echo ""
echo "STEP 2: Deploy to Vercel"
echo "------------------------"
echo ""
echo "1. Go to https://vercel.com/signup"
echo "2. Click 'Continue with GitHub'"
echo "3. Authorize Vercel to access your GitHub"
echo "4. On Vercel dashboard, click 'Add New Project'"
echo "5. Find 'prooflocker' in the list"
echo "6. Click 'Import'"
echo "7. Click 'Deploy' (don't change anything yet)"
echo ""
read -p "Press ENTER once deployment starts..."
echo ""
echo "STEP 3: Add Environment Variables"
echo "----------------------------------"
echo ""
echo "1. On Vercel, go to your project"
echo "2. Click 'Settings' → 'Environment Variables'"
echo "3. Add these variables one by one:"
echo ""
echo "Copy and paste each line into Vercel:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL"
echo "Value: https://ofpzqtbhxajptpstbbme.supabase.co"
echo ""
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcHpxdGJoeGFqcHRwc3RiYm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MTcxMzQsImV4cCI6MjA4MzI5MzEzNH0.h8k8Lx4R2v_y6qJFM1MuFZNoONA7AJZ3zWtyoXXsaHU"
echo ""
echo "DE_API_KEY"
echo "Value: sk_live_UEKT2Y_QS5oiw0urMiZDDMokszo2_LmVF3O6EW5BGbb"
echo ""
echo "DE_TENANT_ID"
echo "Value: 928106cb-34a9-405c-8e21-2ab8d7ecafde"
echo ""
echo "DE_ORG_ID"
echo "Value: 69ab73c5-307d-4445-8a57-f65641d40405"
echo ""
echo "DE_SIGNING_PRIVATE_KEY_HEX"
echo "Value: 5516226c7d0b8fe546df39f1166922a668b0e6fa776872ad616117faa0169d57"
echo ""
echo "DE_API_URL"
echo "Value: https://de-api.constellationnetwork.io/v1"
echo ""
read -p "Press ENTER once you've added all environment variables..."
echo ""
echo "4. Go to 'Deployments' tab"
echo "5. Click '...' menu on the latest deployment"
echo "6. Click 'Redeploy'"
echo ""
echo "🎉 Your app will be live in ~2 minutes!"
echo ""
echo "You'll get a URL like: https://prooflocker.vercel.app"
